PDFINVEST/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pdfapp/', include('pdfapp.urls')),
    url(r'^$', RedirectView.as_view(url='/pdfapp/upload/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdfapp/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import upload_view, edit_view, show_files, sigpae, sigpae_show, sigpae_report, ref_report, books, book_show, book_new

urlpatterns = [
    url(r'^upload/$', upload_view, name='upload'),
    #url(r'^edit/(?P<fileName>[^\.\s/]+\.pdf)$', edit_view, name='edit'),
    url(r'^edit/(?P<filePath>[^\.\s]+)/(?P<fileName>[^\.\s/]+)\.pdf$', edit_view, name='edit'),
    url(r'^files/$', show_files, name='files'),
    url(r'^sigpae/$', sigpae, name='sigpae'),
    url(r'^sigpae/(?P<pk>[0-9]+)$', sigpae_show, name='sigpae_show'),
    url(r'^report/global/$', sigpae_report, name='global_report'),
    url(r'^report/ref/$', ref_report, name='ref_report'),
    url(r'^books/$', books, name='books'),
    url(r'^books/new$', book_new, name='book_new'),
    url(r'^books/(?P<pk>[0-9]+)$', book_show, name='book_show'),
]

pdfapp/models.py
from django.db import models
from .validators import validate_pdf_extension
from .validators import validate_positive_integer
from .validators import validate_credits
from .validators import validate_program_years
from .validators import validate_non_zero
from .validators import validate_days_month
from .validators import validate_years
from .validators import validate_max_hours
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator

from datetime import datetime, date
import re





class Document(models.Model):
    # Document in PDF format to be uploaded to the page.
    
    RE_COURSE_CODE_A = '[A-Z]{2}[ \-]?[0-9]{4}'
    RE_COURSE_CODE_B = '[A-Z]{3}[ \-]?[0-9]{3}'
    
    # The date of the upload.
    date = models.DateTimeField(
        default=datetime.now,
        blank=True,
    )

    # Chosen name of the document.
    name = models.CharField(
        max_length=60,
        blank=True,
    )

    # The uploaded document. Must be in PDF format.    
    docfile = models.FileField(
        upload_to='documents/%Y/%m/%d',
        validators=[validate_pdf_extension],
    )
 
    # HTML textring of the transcript PDF document given.
    html_text_string = models.TextField(
        null=True,
        blank=True,
    )

    # This field is False until the transcription is finished.
    ready_html = models.BooleanField(
        default=False,
    )

    # This field is True while the transcription is in process.
    processing_html = models.BooleanField(
        default=False,
    )

    # The name of the PDF document file.
    file_name = models.TextField(
        default="Error: You Need to get the Filename",
        blank=True,
    )

    # Path containing the PDF document file.
    file_path = models.TextField(
        null=True,
        blank=True,
    )
    
    # Returns a set of courses codes from an html file
    @staticmethod
    def course_codes(filename):
        html_file = open(filename, 'r')
        file_contents = html_file.read()
        possible_codes_a = re.findall(Document.RE_COURSE_CODE_A ,file_contents)
        possible_codes_b = re.findall(Document.RE_COURSE_CODE_B ,file_contents)
        possible_codes = set(possible_codes_a + possible_codes_b)
        return possible_codes
    
    # Avoids to mark the trancription as ready and processing at the same time.
    def clean(self):
        if self.ready_html and self.processing_html:
            raise ValidationError('You can\'t be ready when you\'re \
                                                     processing the html.')

    # Saves Document objects into database.
    def save(self, *args, **kwargs):
        self.full_clean()
        return super(Document, self).save(*args, **kwargs)


class Division(models.Model):
    # Divisions are the academic units in charge of the departments.

    # Name of the division.
    name = models.CharField(
        max_length=60,
        primary_key=True,
    )
    
    # Returns the name of the division.
    def __str__(self):
        return "{}".format(self.name)


class Department(models.Model):
    # Departments are academic units. They usually offer the assignatures.

    # Name of the department.
    name = models.CharField(
        max_length=60,
        primary_key=True,
    )

    # A department should be subscribed to one division.
    division = models.ForeignKey(
        Division,
        on_delete=models.CASCADE,
    )
    
    # Returns the name of the department.
    def __str__(self):
        return "{}".format(self.name)


class Deanery(models.Model):
    # Deaneries are the academic units in charge of the coordinations.

    # Name of the deanery.
    name = models.CharField(
        max_length=60,
        primary_key=True,
    )

    # Returns the name of the deanery.
    def __str__(self):
        return "{}".format(self.name)


class Coordination(models.Model):
    # Coordinations are academic units. They usually manage study programs.
    # They can offer assignatures in a few cases.

    # Name of the coordination.
    name = models.CharField(
        max_length=60,
        primary_key=True,
    )

    # A coordination can be subscribed to many deaneries.
    deanery = models.ManyToManyField(
        Deanery,
    )

    # Returns the name of the coordination.
    def __str__(self):
        return "{}".format(self.name)

class AdditionalName(models.Model):
    # Additional fields names to be added into programs.

    # Name of the field
    name = models.CharField(
        max_length=30,
        unique=True,
    )

    def __str__(self):
        return "{}".format(self.name)

class AdditionalField(models.Model):
    # Additional field text.

    # Description of the field.
    description = models.TextField(
        null=True,
        blank=True,
    )

    # Name of the field.
    name = models.ForeignKey(
        AdditionalName,
        on_delete=models.CASCADE,
    )

class Code(models.Model):
    # Code.
    code = models.CharField(
        max_length=3,
        primary_key=True,
        verbose_name='Código',
    )
    # A department is responsible for many codes.
    department = models.ForeignKey(
        Department,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{}".format(self.code)

# Autors of recommended sources.
class Author(models.Model):
    first_name = models.CharField(
        max_length=20,
        verbose_name='Primer nombre',
    )

    second_name = models.CharField(
        max_length=20,
        blank=True,
        verbose_name='Segundo nombre',
    )

    first_surname = models.CharField(
        max_length=20,
        verbose_name='Primer apellido',
    )

    second_surname = models.CharField(
        max_length=20,
        blank=True,
        verbose_name='Segundo apelido',
    )
    def __str__(self): 
        return self.first_surname
    class Meta:
        ordering = ['first_surname','first_name']

# Recommended sources.
class Reference(models.Model):
    # Author of the author's book.
    author = models.ManyToManyField(
        Author,
        blank=True,
        verbose_name='Autor',
    )

    # Book's title.
    title = models.TextField(
        verbose_name='Título',
    )

    # Publishing house of the book.
    editorial = models.CharField(
        max_length=30,
        blank=True,
        verbose_name='Editorial',
    )

    # Recommended edition.
    edition_number = models.PositiveIntegerField(
        validators=[validate_non_zero],
        blank=True,
        null=True,
        verbose_name='No. Edición',
    )


    # Recommended year.
    year = models.PositiveIntegerField(
        validators=[validate_years],
        blank=True,
        null=True,
        verbose_name='Año',
    )

    def __str__(self):
        rep = str(self.title)
        if self.edition_number is not None and self.edition_number != "":
             rep += " Edicion Nro. " + str(self.edition_number)
        if self.year is not None and self.year != "":
             rep += " Año " + str(self.year)
        if self.editorial is not None and self.editorial != "":
             rep += " Editorial " + str(self.editorial)
        return "{}".format(rep)

class Program(models.Model):
    # The program of an assignature and all its related data.

    # All posible trimesters, including the summer intensive.
    TRIMESTER = (
        ('0Ene-Mar', 'Enero-Marzo'),
        ('1Abr-Jul', 'Abril-Julio'),
        ('2Jul-Ago', 'Julio-Agosto (Intensivo)'),
        ('3Sep-Dic', 'Septiembre-Diciembre'),
    )
    MONTH = (
        (1, 'Enero'),
        (2, 'Febrero'),
        (3, 'Marzo'),
        (4, 'Abril'),
        (5, 'Mayo'),
        (6, 'Junio'),
        (7, 'Julio'),
        (8, 'Agosto'),
        (9, 'Septiembre'),
        (10, 'Octubre'),
        (11, 'Noviembre'),
        (12, 'Diciembre'),
    )

    # PDF document associated to the program.
    document = models.OneToOneField(
        Document,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    # The code of the assignature, divided in its department code and a number.
    code = models.ForeignKey(
        Code,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Código Departamento',
    )
    number = models.CharField(
        max_length=4,
        blank=True,
        validators=[RegexValidator(regex='^\d{3,4}$',
                    message='Debe estar formado por 3 o 4 dígitos.')],
        verbose_name='Código Número',
    )

    # The suggested code is approved.
    approved_code = models.BooleanField(
        default=False,
    )

    # The name of the assignature.
    denomination = models.CharField(
        blank=True, 
        max_length=60,
        verbose_name='Denominación',
    )

    # Date of validity.
    validity_date_y = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name='Año',
        validators=[validate_program_years]
    )
    validity_date_m = models.PositiveIntegerField(
        choices=MONTH,
        blank=True,
        null=True,
        verbose_name='Mes',
    )

    validity_date_d = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name='Día',
        validators=[validate_days_month],
    )

    # Proposed year of validity of the program.
    validity_year = models.PositiveIntegerField(
        null=True,
        blank=True,
        verbose_name='Año propuesto',
        validators=[validate_program_years],
    )

    # Proposed trimester of validity of the program.
    validity_trimester = models.CharField(
        max_length=10,
        choices=TRIMESTER,
        blank=True, 
        null=True,
        verbose_name='Trimestre propuesto',
    )

    # Number of hours of theory in the assignature.
    theory_hours = models.PositiveIntegerField(
        blank=True,

pdfapp/templates/book.html
{% load staticfiles %}
{% load formset_tags %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>PDFINVEST The Best Invest</title>
        <script src="{% static "hide.js" %}" type="text/javascript"></script>
        <script src="{% static "cookies.js" %}" type="text/javascript"></script>

        <!-- Jquery and Chained Selection-->
        <script src="{% static "/js/jquery-1.10.2.min.js" %}"></script>
        <!-- Formset JS-->
        <script src="{% static "/js/jquery.formset.js" %}"></script>

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
        
        <!-- Compiled and minified JavaScript -->
        <script src="{% static "js/materialize.min.js" %}"></script>

        <!-- Materialize icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    </head>

    <body>

    <nav>
        <div class="nav-wrapper red darken-3">
            <a href="/pdfapp/upload/" class="brand-logo">&ensp; Conversor de PDF a HTML</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/pdfapp/files/">Archivos</a></li>
                <li><a href="/pdfapp/sigpae/">SIGPAE</a></li>
                <li>
                    <a class='dropdown-button btn red darken-4' href='#' data-hover="true" data-beloworigin="" data-activates='dropdown1'>Reportes</a>
                    <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="/pdfapp/report/global/">Reportes Globales</a></li>
                        <li><a href="/pdfapp/report/ref/">Fuentes de Información</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <div style="text-align: left; margin: 1% 3% 3% 8%;">
        <h2>{{ title }}</h2>
        {% if error %}
            <div class="error red-text longText">{{ error }}</div>
        {% else %}
        {% if pk %}
        <form class="col s12" method="POST" action="{% url 'book_show' pk=pk  %}" >
        {% else %}
        <form class="col s12" method="POST" action="{% url 'book_new' %}" >
        {% endif %}
        <div>
            {% csrf_token %}
            
                <div class="error red-text longText">{{ book.non_field_errors }}</div>
                {% for hidden in book.hidden_fields %} {{ hidden }} {% endfor %}
                {% for field in book%}
                <div class="input-field">
                    {{ field }}
                    {{ field.label_tag }} 
                    {{ field.errors }}
                </div>
                {% endfor %}
                <h4>Autores</h4>
                <div id="authorsForm" data-formset-prefix="{{ authorsForm.prefix }}">
                    {{ authorsForm.management_form }}

                    <div data-formset-body>
                        <!-- New forms will be inserted in here -->
                        {% for form in authorsForm %}
                            <div class="error red-text longText">{{ form.non_field_errors }}</div>
                            <div data-formset-form >
                                {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
                                <div class="input-field">
                                    {{ form.first_name }}
                                    {{ form.first_name.label_tag }} 
                                    {{ form.first_name.errors }}
                                </div>
                                <div class="input-field">
                                    {{ form.second_name }}
                                    {{ form.second_name.label_tag }} 
                                    {{ form.second_name.errors }}
                                </div>
                                <div class="input-field">
                                    {{ form.first_surname }}
                                    {{ form.first_surname.label_tag }} 
                                    {{ form.first_surname.errors }}
                                </div>
                                <div class="input-field">
                                    {{ form.second_surname }}
                                    {{ form.second_surname.label_tag }} 
                                    {{ form.second_surname.errors }}
                                </div>
                                <div class="hidden">{{ form.DELETE }}</div>
                                <div class="hidden">{{ form.ORDER }}</div>
                                <button type="button" class="save waves-effect red darken-3 btn" data-formset-delete-button>Borrar Autor</button>
                                <br><br>
                            </div>
                        {% endfor %}
                    </div>

                    <!-- The empty form template. By wrapping this in a <script> tag, the
                    __prefix__ placeholder can easily be replaced in both attributes and
                    any scripts -->
                    <script type="form-template" data-formset-empty-form>
                        {% escapescript %}
                            <div data-formset-form>
                                {% for hidden in authorsForm.empty_form.hidden_fields %} {{ hidden }} {% endfor %}
                                <div class="input-field">
                                    {{ authorsForm.empty_form.first_name }}
                                    {{ authorsForm.empty_form.first_name.label_tag }} 
                                    {{ authorsForm.empty_form.first_name.errors }}
                                </div>
                                <div class="input-field">
                                    {{ authorsForm.empty_form.second_name }}
                                    {{ authorsForm.empty_form.second_name.label_tag }} 
                                    {{ authorsForm.empty_form.second_name.errors }}
                                </div>
                                <div class="input-field">
                                    {{ authorsForm.empty_form.first_surname }}
                                    {{ authorsForm.empty_form.first_surname.label_tag }} 
                                    {{ authorsForm.empty_form.first_surname.errors }}
                                </div>
                                <div class="input-field">
                                    {{ authorsForm.empty_form.second_surname }}
                                    {{ authorsForm.empty_form.second_surname.label_tag }} 
                                    {{ authorsForm.empty_form.second_surname.errors }}
                                </div>
                                <div class="hidden">{{ authorsForm.empty_form.DELETE }}</div>
                                <div class="hidden">{{ authorsForm.empty_form.ORDER }}</div>
                                <button type="button" class="save waves-effect red darken-3 btn" data-formset-delete-button>Borrar Autor</button>
                                <br><br>
                            </div>
                        {% endescapescript %}
                    </script>

                    <!-- This button will add a new form when clicked -->
                    <input type="button" class="save waves-effect red darken-3 btn" value="Agregar Autor" data-formset-add>

                    <script>jQuery(function($) {
                        $("#authorsForm").formset({
                            animateForms: true,
                            reorderMode: 'dom',
                        });
                    });</script>


                </div>
            
        </div>
        <br>
        <button type="submit" class="save waves-effect red darken-3 btn">Guardar Cambios</button>
        </form>
        {% endif %}
    </div>
    </body>
</html> 

pdfapp/templates/books.html
{% load staticfiles %}
{% load formset_tags %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>PDFINVEST The Best Invest</title>
        <script src="{% static "hide.js" %}" type="text/javascript"></script>
        <script src="{% static "cookies.js" %}" type="text/javascript"></script>

        <!-- Jquery and Chained Selection-->
        <script src="{% static "/js/jquery-1.10.2.min.js" %}"></script>

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
        
        <!-- Compiled and minified JavaScript -->
        <script src="{% static "js/materialize.min.js" %}"></script>

        <!-- Materialize icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


    </head>

    <body>

    <nav>
        <div class="nav-wrapper red darken-3">
            <a href="/pdfapp/upload/" class="brand-logo">&ensp; Conversor de PDF a HTML</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/pdfapp/files/">Archivos</a></li>
                <li><a href="/pdfapp/sigpae/">SIGPAE</a></li>
                <li>
                    <a class='dropdown-button btn red darken-4' href='#' data-hover="true" data-beloworigin="" data-activates='dropdown1'>Reportes</a>
                    <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="/pdfapp/report/global/">Reportes Globales</a></li>
                        <li><a href="/pdfapp/report/ref/">Fuentes de Información</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <h2>Referencias en Sistema</h2>
    <div style="text-align: left; margin: 1% 3% 3% 8%;">
    <button class="waves-effect red darken-3 btn" onClick="window.open('{% url 'book_new' %}', '_blank'); return false;">Nueva Referencia</button>
    <ul class="collection">
    {% for book in books%}
        <a class="collection-item" onClick="window.open('{% url 'book_show' pk=book.pk %}', '_blank'); return false;"> {% for author in book.author.all%} {{ author.first_surname }}, {{ author.first_name }}. {% empty %}{% endfor %} {{ book.title }}.{% if book.editorial %} Editorial {{ book.editorial }}.{% endif %}{% if book.edition_number %} Edición {{ book.edition_number }}.{% endif %}{% if book.year %} Año {{ book.year }}{% endif %}</a>
    {% empty %}
    {% endfor %}
    </ul>
    </div>
    </body>
</html> 

pdfapp/templates/global_report.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>PDFINVEST The Best Invest</title>
        <script src="{% static "hide.js" %}" type="text/javascript"></script>
        <script src="{% static "cookies.js" %}" type="text/javascript"></script>

        <!-- Jquery and Chained Selection-->
        <script src="{% static "/js/jquery-1.10.2.min.js" %}"></script>

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
        
        <!-- Compiled and minified JavaScript -->
        <script src="{% static "js/materialize.min.js" %}"></script>

        <!-- Materialize icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <script src="{% static "globalreportHandler.js" %}"></script> 

    </head>

    <body>

    <nav>
        <div class="nav-wrapper red darken-3">
            <a href="/pdfapp/upload/" class="brand-logo">&ensp; Conversor de PDF a HTML</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/pdfapp/files/">Archivos</a></li>
                <li><a href="/pdfapp/sigpae/">SIGPAE</a></li>
                <li>
                    <a class='dropdown-button btn red darken-4' href='#' data-hover="true" data-beloworigin="" data-activates='dropdown1'>Reportes</a>
                    <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="/pdfapp/report/global/">Reportes Globales</a></li>
                        <li><a href="/pdfapp/report/ref/">Fuentes de Información</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <form method="POST" action="{% url 'global_report' %}" >
    {% csrf_token %}
    <table style="width: 100%;">
        <tbody>
            <tr>
                <td><div class="input-field">
                    {{ report_form.code }}
                    {{ report_form.code.label_tag }}
                    {{ report_form.code.errors }}
                </div></td>
                <td><div class="input-field">
                    {{ report_form.report_type }}
                    {{ report_form.report_type.label_tag }}
                    {{ search_form.report_type.errors }}
                </div></td>
                <td><button type="submit" class="save waves-effect red darken-3 btn">Buscar</button></td>
            </tr>
        </tbody>
    </table>
    </form>
    <div style="text-align: left; margin: 1% 3% 3% 8%;">
    {{ report_form.non_field_errors }}
    <ul class="collection">
    {% for program in resultT%}
        <a class="collection-item" href={% url 'edit' filePath=program.document.file_path fileName=program.document.file_name %}>{{ program.code.code }}{{ program.number }} : {{ program.get_validity_trimester_display|default:"trimestre de validez desconocido," }} {{ program.validity_year|default:"año de validez desconocido" }}</a>
    {% empty %}
    {% endfor %}
    {% for program in resultP%}
        <a class="collection-item" href={% url 'sigpae_show' pk=program.pk %}>{{ program.codigo }} : {{ program.get_fecha_vigTrim_display }} {{ program.fecha_vigAno }}</a>
    {% empty %}
    {% endfor %}
    </ul>
    </div>
    </body>
</html> 

pdfapp/templates/ref_report.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>PDFINVEST The Best Invest</title>
        <script src="{% static "hide.js" %}" type="text/javascript"></script>
        <script src="{% static "cookies.js" %}" type="text/javascript"></script>

        <!-- Jquery and Chained Selection-->
        <script src="{% static "/js/jquery-1.10.2.min.js" %}"></script>

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
        
        <!-- Compiled and minified JavaScript -->
        <script src="{% static "js/materialize.min.js" %}"></script>

        <!-- Materialize icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <script src="{% static "reportHandler.js" %}"></script> 

    </head>

    <body>

    <nav>
        <div class="nav-wrapper red darken-3">
            <a href="/pdfapp/upload/" class="brand-logo">&ensp; Conversor de PDF a HTML</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/pdfapp/files/">Archivos</a></li>
                <li><a href="/pdfapp/sigpae/">SIGPAE</a></li>
               <li>
                    <a class='dropdown-button btn red darken-4' href='#' data-hover="true" data-beloworigin="" data-activates='dropdown1'>Reportes</a>
                    <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="/pdfapp/report/global/">Reportes Globales</a></li>
                        <li><a href="/pdfapp/report/ref/">Fuentes de Información</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <form method="POST" action="{% url 'ref_report' %}" >
    {% csrf_token %}
    <table style="width: 100%;">
        <tbody>
            <tr>
                <td><div class="input-field">
                    {{ report_form.code }}
                    {{ report_form.code.label_tag }}
                    {{ report_form.code.errors }}
                </div></td>
                <td><div class="input-field">
                    {{ report_form.year }}
                    {{ report_form.year.label_tag }}
                    {{ search_form.year.errors }}
                </div></td>
                <td><div class="input-field">
                    {{ report_form.trimester }}
                    {{ report_form.trimester.label_tag }}
                    {{ report_form.trimester.errors }}
                <td><button type="submit" class="save waves-effect red darken-3 btn">Buscar</button></td>
            </tr>
        </tbody>
    </table>
    </form>
    <div style="text-align: left; margin: 1% 3% 3% 8%;">
    {{ report_form.non_field_errors }}
    <ul class="collection">
    {% for source in results%}
        <a class="collection-item" href="#">{{ source.author.all|join:", " }}, {{ source.title }}, {{ source.editorial|default:"editorial desconocida" }}, edición nro. {{ source.edition_number|default:"desconocido" }}, {{ source.year|default:"año desconocido" }} </a>
    {% empty %}
    {% endfor %}
    </ul>
    </div>
    </body>
</html> 

pdfapp/templates/sigpae.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>PDFINVEST The Best Invest</title>
        <script src="{% static "hide.js" %}" type="text/javascript"></script>
        <script src="{% static "cookies.js" %}" type="text/javascript"></script>

        <!-- Jquery and Chained Selection-->
        <script src="{% static "/js/jquery-1.10.2.min.js" %}"></script>

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
        
        <!-- Compiled and minified JavaScript -->
        <script src="{% static "js/materialize.min.js" %}"></script>

        <!-- Materialize icons -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- SIGPAE Handler Script -->
        <script src="{% static "sigpaeHandler.js" %}"></script> 
    </head>

    <body>

    <nav>
        <div class="nav-wrapper red darken-3">
            <a href="/pdfapp/upload/" class="brand-logo">&ensp; Conversor de PDF a HTML</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/pdfapp/files/">Archivos</a></li>
                <li><a href="/pdfapp/sigpae/">SIGPAE</a></li>
                <li>
                    <a class='dropdown-button btn red darken-4' href='#' data-hover="true" data-beloworigin="" data-activates='dropdown1'>Reportes</a>
                    <ul id='dropdown1' class='dropdown-content'>
                        <li><a href="/pdfapp/report/global/">Reportes Globales</a></li>
                        <li><a href="/pdfapp/report/ref/">Fuentes de Información</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <form method="POST" action="{% url 'sigpae' %}" >
    {% csrf_token %}
    <table style="width: 100%;">
        <tbody>
            <tr>
                <td><div class="input-field">{{ search_form.code }} {{ search_form.code.label_tag }} {{ search_form.code.errors }}</div></td>
                <td><div class="input-field">{{ search_form.year }} {{ search_form.year.label_tag }} {{ search_form.year.errors }}</div></td>
                <td><div class="input-field">{{ search_form.trimester }} {{ search_form.trimester.label_tag }} {{ search_form.trimester.errors }}</div></td>
                <td><button type="submit" class="save waves-effect red darken-3 btn">Buscar</button></td>
            </tr>
        </tbody>
    </table>
    </form>
    <div style="text-align: left; margin: 1% 3% 3% 8%;">
    {{ search_form.non_field_errors }}
    <ul class="collection">
    {% for program in results%}
        <a class="collection-item" href={% url 'sigpae_show' pk=program.pk %}>{{ program.codigo }} : {{ program.get_fecha_vigTrim_display }} {{ program.fecha_vigAno }}</a>
    {% empty %}
    {% endfor %}
    </ul>
    </div>
    </body>
</html> 